<?php

namespace App\Http\Controllers\Public;

use App\Http\Controllers\Controller;
use Illuminate\View\View;

class MarketingPageController extends Controller
{
    private const PAGES = [
        'features' => ['type' => 'feature', 'title' => 'Features', 'intro' => 'A connected toolkit for running admissions, records, classes, communication, finance, and reporting from one clear workspace.', 'items' => ['Unified school records', 'Role-aware portals', 'Operational reporting', 'Configurable setup'], 'benefits' => ['Reduce duplicate admin work', 'Keep every team aligned', 'Give leaders cleaner visibility']],
        'student-management' => ['type' => 'feature', 'title' => 'Student Management', 'intro' => 'Keep student profiles, enrollment history, guardians, class placement, and academic context organized in one dependable record.', 'items' => ['Student profiles', 'Guardian details', 'Class enrollment', 'Academic history'], 'benefits' => ['Find student information faster', 'Support cleaner admissions handoff', 'Improve record accuracy']],
        'attendance' => ['type' => 'feature', 'title' => 'Attendance', 'intro' => 'Record attendance quickly and connect daily presence data to reports, communication, and school oversight.', 'items' => ['Daily attendance', 'Subject attendance', 'Absence visibility', 'Attendance summaries'], 'benefits' => ['Save classroom time', 'Spot attendance patterns earlier', 'Keep administrators informed']],
        'academics' => ['type' => 'feature', 'title' => 'Academics', 'intro' => 'Bring classes, subjects, assessments, exams, lesson planning, results, and promotion workflows into one academic system.', 'items' => ['Classes and subjects', 'Assignments and exams', 'Lesson plans', 'Results and promotions'], 'benefits' => ['Simplify term workflows', 'Support teachers with focused tools', 'Keep academic records consistent']],
        'fees-payments' => ['type' => 'feature', 'title' => 'Fees & Payments', 'intro' => 'Track school fees, assessments, balances, part-payments, expenses, and receipts with clear finance workflows.', 'items' => ['Fee assessments', 'Part-payment tracking', 'Receipts and balances', 'Finance dashboards'], 'benefits' => ['Improve collection visibility', 'Reduce manual reconciliation', 'Give families clearer balances']],
        'communication' => ['type' => 'feature', 'title' => 'Communication', 'intro' => 'Keep administrators, teachers, students, and parents connected through announcements, notifications, and feedback workflows.', 'items' => ['Announcements', 'Notifications', 'Parent and student updates', 'Feedback records'], 'benefits' => ['Reduce repeated calls', 'Share updates in one place', 'Strengthen school-home trust']],
        'reports' => ['type' => 'feature', 'title' => 'Reports', 'intro' => 'Turn attendance, academics, fees, and operations data into useful views leaders can understand and act on.', 'items' => ['Attendance reports', 'Finance summaries', 'Academic records', 'Exportable data'], 'benefits' => ['Make faster decisions', 'See operational trends', 'Prepare cleaner records']],
        'pricing' => ['type' => 'resource', 'title' => 'Pricing', 'intro' => 'Choose a SchoolOS plan around your school size, operating needs, and rollout goals.', 'items' => ['Starter setup for smaller schools', 'Professional tools for growing teams', 'Enterprise support for larger operations'], 'cta' => 'Start your school setup'],
        'demo' => ['type' => 'resource', 'title' => 'Book a Demo', 'intro' => 'See how SchoolOS can fit your admissions, attendance, academics, communication, fees, and reporting workflows.', 'items' => ['Walk through core workflows', 'Discuss your school structure', 'Plan a practical rollout'], 'cta' => 'Get started first'],
        'school-admins' => ['type' => 'solution', 'title' => 'For School Admins', 'intro' => 'Give school leaders a calmer way to manage people, records, finance, academics, and daily operations.', 'items' => ['Scattered records', 'Slow reporting', 'Manual follow-up'], 'features' => ['Dashboards', 'Student management', 'Fee tracking', 'Reports'], 'benefits' => ['Better visibility', 'Cleaner oversight', 'Less repetitive admin work']],
        'teachers' => ['type' => 'solution', 'title' => 'For Teachers', 'intro' => 'Help teachers manage attendance, lesson plans, assignments, exams, and classroom updates from a focused workspace.', 'items' => ['Paper-heavy routines', 'Disconnected academic tasks', 'Hard-to-track submissions'], 'features' => ['Attendance', 'Assignments', 'Lesson plans', 'Exams'], 'benefits' => ['More teaching time', 'Clearer classroom records', 'Simpler academic workflows']],
        'parents' => ['type' => 'solution', 'title' => 'For Parents', 'intro' => 'Give families clearer access to the information they need about attendance, fees, results, and school updates.', 'items' => ['Repeated status calls', 'Late updates', 'Unclear fee balances'], 'features' => ['Parent portal', 'Announcements', 'Fees', 'Results'], 'benefits' => ['Stronger trust', 'Better visibility', 'Fewer information gaps']],
        'students' => ['type' => 'solution', 'title' => 'For Students', 'intro' => 'Give learners a simple place to follow assignments, timetables, announcements, fees, and academic progress.', 'items' => ['Missed updates', 'Scattered tasks', 'Unclear schedules'], 'features' => ['Student portal', 'Assignments', 'Timetable', 'Results'], 'benefits' => ['Better organization', 'Clearer responsibilities', 'More independent learning']],
        'staff' => ['type' => 'solution', 'title' => 'For Staff', 'intro' => 'Support non-teaching staff with simple access to the operational tools and records they need each day.', 'items' => ['Manual check-ins', 'Fragmented workflows', 'Limited visibility'], 'features' => ['Staff portal', 'Attendance', 'Operations records', 'Notifications'], 'benefits' => ['Clearer daily routines', 'Better accountability', 'Less manual coordination']],
        'private-schools' => ['type' => 'solution', 'title' => 'For Private Schools', 'intro' => 'Run enrollment, fee collection, academics, communication, and reporting with a platform shaped around growing schools.', 'items' => ['Fee pressure', 'Parent communication load', 'Manual records'], 'features' => ['Fees', 'Parent portal', 'Academics', 'Reports'], 'benefits' => ['More professional operations', 'Cleaner parent experience', 'Better growth visibility']],
        'multi-campus' => ['type' => 'solution', 'title' => 'For Multi-campus Schools', 'intro' => 'Create consistent workflows across campuses while keeping leaders close to records, reporting, and operations.', 'items' => ['Inconsistent processes', 'Separated records', 'Slow oversight'], 'features' => ['Central records', 'Reports', 'Role access', 'Operational dashboards'], 'benefits' => ['Standardized workflows', 'Better leadership visibility', 'Easier expansion planning']],
        'help' => ['type' => 'resource', 'title' => 'Help Center', 'intro' => 'Find practical guidance for setting up SchoolOS and managing common school workflows.', 'items' => ['Setup guidance', 'Role-based workflows', 'Troubleshooting support'], 'cta' => 'Contact support'],
        'docs' => ['type' => 'resource', 'title' => 'Documentation', 'intro' => 'Learn how SchoolOS is organized across school setup, portals, modules, permissions, and daily workflows.', 'items' => ['School setup', 'User roles', 'Academic records', 'Finance workflows'], 'cta' => 'Start setup'],
        'getting-started' => ['type' => 'resource', 'title' => 'Getting Started', 'intro' => 'Create your school workspace, configure the basics, invite your team, and begin moving daily work into SchoolOS.', 'items' => ['Create your school', 'Choose modules', 'Set up classes', 'Invite users'], 'cta' => 'Get started'],
        'faqs' => ['type' => 'resource', 'title' => 'FAQs', 'intro' => 'Answers to common questions about SchoolOS setup, modules, parent access, fees, and school operations.', 'items' => ['Can parents access SchoolOS?', 'Can schools track part-payments?', 'Can schools choose modules?', 'Can SchoolOS manage report cards?'], 'cta' => 'Book a demo'],
        'support' => ['type' => 'resource', 'title' => 'Contact Support', 'intro' => 'Get help with SchoolOS setup, configuration, onboarding, and day-to-day product questions.', 'items' => ['Email support@schoolos.com', 'Ask setup questions', 'Get workflow guidance'], 'cta' => 'Send an email'],
        'about' => ['type' => 'resource', 'title' => 'About SchoolOS', 'intro' => 'SchoolOS is built to help schools simplify administration, improve communication, and keep education at the center of daily operations.', 'items' => ['Modern school operations', 'Connected communities', 'Practical tools for real school days'], 'cta' => 'Explore features'],
        'contact' => ['type' => 'resource', 'title' => 'Contact', 'intro' => 'Reach the SchoolOS team for questions about setup, demos, support, or school rollout planning.', 'items' => ['support@schoolos.com', 'Product questions', 'Rollout planning'], 'cta' => 'Contact support'],
        'careers' => ['type' => 'resource', 'title' => 'Careers', 'intro' => 'Join work focused on building dependable education software for schools, educators, families, and students.', 'items' => ['Product engineering', 'Customer support', 'Education operations'], 'cta' => 'Contact us'],
        'partners' => ['type' => 'resource', 'title' => 'Partners', 'intro' => 'Work with SchoolOS to help schools adopt practical digital operations and better connected workflows.', 'items' => ['Implementation partners', 'Education consultants', 'Technology partners'], 'cta' => 'Start a conversation'],
        'privacy' => ['type' => 'legal', 'title' => 'Privacy Policy', 'intro' => 'SchoolOS treats school, student, parent, and staff data with care and uses it to provide secure school management services.', 'items' => ['We collect information needed to create accounts, manage school records, and operate the platform.', 'We use data to deliver SchoolOS features, provide support, improve reliability, and protect accounts.', 'Schools remain responsible for the accuracy of records they enter and for granting appropriate user access.']],
        'terms' => ['type' => 'legal', 'title' => 'Terms of Service', 'intro' => 'These terms describe responsible use of SchoolOS and the relationship between SchoolOS, schools, and authorized users.', 'items' => ['Users should access only the school data their role permits.', 'Schools are responsible for managing users, roles, and records in their workspace.', 'SchoolOS may update product features to improve security, reliability, and usability.']],
        'cookies' => ['type' => 'legal', 'title' => 'Cookie Policy', 'intro' => 'SchoolOS uses essential browser storage and cookies to keep sessions, preferences, and security features working properly.', 'items' => ['Essential cookies support login sessions and security protections.', 'Preference storage helps remember theme and interface choices.', 'Schools and users can manage browser-level cookie settings where supported.']],
    ];

    public function show(string $page): View
    {
        abort_unless(array_key_exists($page, self::PAGES), 404);

        return view('public.marketing-page', [
            'page' => self::PAGES[$page],
            'pageKey' => $page,
        ]);
    }
}
